dist: trusty
sudo: required

language: python
python:
    - "2.7"
cache: pip

before_install:
  - lsb_release -a
  - sudo add-apt-repository ppa:deluge-team/develop -y
  - sudo apt-get update

# command to install dependencies
install:
  - bash -c "echo $APTPACKAGES"
  - sudo apt-get install $APTPACKAGES
  - pip install tox
  # the next part is for the security tests only.
  - wget https://github.com/drwetter/testssl.sh/archive/v2.9.5-5.tar.gz -O testssl.tar.gz
  - tar -xvzf testssl.tar.gz
  - mv -t deluge/tests/data testssl.sh-2.9.5-5/testssl.sh testssl.sh-2.9.5-5/etc/

env:
  global:
    - APTPACKAGES="python-libtorrent"
    - APTPACKAGES_GTKUI="python-gi python-gi-cairo gir1.2-gtk-3.0"
    - DISPLAY=:99.0

matrix:
  include:
    - env: TOX_ENV=pydef
    - if: commit_message =~ SECURITY_TEST
      env: TOX_ENV=security
    - env: TOX_ENV=flake8
    #- env:  TOX_ENV=flake8-complexity
    - env: TOX_ENV=docs
    #- env: TOX_ENV=todo
    - env: TOX_ENV=trial              APTPACKAGES="$APTPACKAGES $APTPACKAGES_GTKUI"
    - env: TOX_ENV=pygtkui            APTPACKAGES="$APTPACKAGES $APTPACKAGES_GTKUI"
    #- env: TOX_ENV=testcoverage       APTPACKAGES="$APTPACKAGES $APTPACKAGES_GTKUI"
    - env: TOX_ENV=plugins

virtualenv:
  system_site_packages: true

# We use xvfb for the GTKUI tests
before_script:
  - export PYTHONPATH=$PYTHONPATH:$PWD
  - python -c "import libtorrent as lt; print lt.__version__"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - echo '2.0.0.dev0' > RELEASE-VERSION

script:
  - bash -c "echo $DISPLAY"
  - tox -e $TOX_ENV
